# Generated by Django 5.2 on 2025-04-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_firebase_uid_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firebase_uid',
        ),
    ]
