# Generated by Django 5.1.8 on 2025-04-19 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('citizen', 'Citizen'), ('law_enforcement', 'Law Enforcement'), ('admin', 'Admin')], default='citizen', help_text='Role allowed to view this statistic', max_length=50)),
                ('incident_type', models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('fraud', 'Fraud'), ('vandalism', 'Vandalism'), ('other', 'Other')], default='other', max_length=50)),
                ('total_reports', models.PositiveIntegerField(default=0, help_text='Total number of reports for this type and role')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Start of reporting period')),
                ('end_date', models.DateField(blank=True, help_text='End of reporting period', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated timestamp')),
                ('notification_type', models.CharField(choices=[('acknowledgment', 'Acknowledgment of Submission'), ('status_update', 'Status Update'), ('resolution', 'Resolution Notification'), ('new_incident', 'New Incident Report'), ('geo_fence', 'Geo-fenced Notification'), ('crime_trend', 'Crime Trend Report'), ('public_safety', 'Public Safety Alert'), ('follow_up', 'Report Follow-Up')], default='acknowledgment', max_length=50)),
            ],
            options={
                'verbose_name': 'Crime Statistics',
                'verbose_name_plural': 'Crime Statistics',
                'ordering': ['-updated_at'],
                'unique_together': {('incident_type', 'user_role', 'status')},
            },
        ),
    ]
