# Generated by Django 5.1.6 on 2025-03-28 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
