# Generated by Django 5.1.6 on 2025-04-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_latitude_report_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/images/'),
        ),
        migrations.AddField(
            model_name='report',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reports/videos/'),
        ),
    ]
