# Generated by Django 5.2 on 2025-04-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_image_report_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
        migrations.RemoveField(
            model_name='report',
            name='video',
        ),
    ]
