# Generated by Django 5.2 on 2025-04-13 00:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_sent_at'),
        ('reports', '0007_alter_report_options_remove_report_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('acknowledgment', 'Acknowledgment of Submission'), ('status_update', 'Status Update'), ('resolution', 'Resolution Notification'), ('new_incident', 'New Incident Report'), ('geo_fence', 'Geo-fenced Notification'), ('crime_trend', 'Crime Trend Report'), ('public_safety', 'Public Safety Alert'), ('follow_up', 'Report Follow-Up')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='related_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
