# Generated by Django 5.1.8 on 2025-04-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_options_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('law_enforcement', 'Law Enforcement'), ('citizen', 'Citizen')], help_text='Optional. Used when targeting users by role rather than a specific user.', max_length=50, null=True),
        ),
    ]
